#!/bin/bash
# Скрипт postinstall для автоматической установки принтера Samsung SCX-4200

# Путь к PPD-файлу, который будет установлен в систему
PPD_PATH="/Library/Printers/SCX-4200.ppd"

# Имя принтера в системе
PRINTER_NAME="Samsung_SCX_4200"

# Добавляем принтер через lpadmin (ключ -E включает принтер)
# Команда требует прав администратора
/usr/sbin/lpadmin -p "$PRINTER_NAME" -P "$PPD_PATH" -E

# (Опционально) Устанавливаем принтер по умолчанию
/usr/sbin/lpoptions -d "$PRINTER_NAME"

exit 0
